# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 19:46
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0002_auto_20160729_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=100)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.CharField(max_length=100)),
                ('scope', models.CharField(max_length=150)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='twentythreeandme.User')),
            ],
        ),
        migrations.AlterField(
            model_name='genotype',
            name='converted_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/converted/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/23andme/converted'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='genotype_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/raw/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/23andme/raw'), upload_to=''),
        ),
    ]
