# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0003_auto_20161201_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
