# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0004_remove_user_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apiuserid',
            new_name='api_user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
