# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-14 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0005_auto_20161206_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_user_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
    ]
