# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0006_auto_20161214_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='genotype',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
