# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-27 20:37
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0007_auto_20170321_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwentyThreeAndMeSettigs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grant_type', models.CharField(max_length=100)),
                ('response_type', models.CharField(max_length=10)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('redirct_uri', models.URLField()),
                ('scope', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='genotype',
            name='converted_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/converted/', location='/Users/andreleon/PycharmProjects/gene-pc-api/data/23andme/converted'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='genotype_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/raw/', location='/Users/andreleon/PycharmProjects/gene-pc-api/data/23andme/raw'), upload_to=''),
        ),
    ]
