# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-27 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0008_auto_20170627_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwentyThreeAndMeSettigs',
            new_name='TwentyThreeAndMeSettings',
        ),
    ]
