# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-28 22:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentythreeandme', '0010_auto_20170627_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='redirct_uri',
            new_name='redirect_uri',
        ),
        migrations.AlterField(
            model_name='genotype',
            name='converted_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/converted/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/23andme/converted'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='genotype',
            name='genotype_file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/23andme/raw/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/23andme/raw'), upload_to=''),
        ),
    ]
