# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 00:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenotypes',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phenotypes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskscores',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
