# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to='gene_pc_api.Activity'),
        ),
    ]
