# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-07 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0002_auto_20160606_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
