# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0002_auto_20160422_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
