# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0003_auto_20160607_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenotype',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='riskscore',
            name='datatype',
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='condition',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='gene_pc_api.Condition'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='population',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='gene_pc_api.Population'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='value',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
