# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0004_auto_20160609_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='study_task_identifier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
