# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0005_activity_study_task_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
