# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0006_riskscore_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystatus',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to='gene_pc_api.Activity'),
        ),
        migrations.AlterField(
            model_name='activitystatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='gene_pc_api.Condition'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to='gene_pc_api.Population'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
