# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0007_auto_20160616_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_identifier', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=1000)),
                ('activity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_answers', to='gene_pc_api.Activity')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='phenotype',
            name='user',
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='value',
            field=models.FloatField(blank=True, default=-1.0, max_length=100),
        ),
        migrations.DeleteModel(
            name='Phenotype',
        ),
    ]
