# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 17:13
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0011_auto_20160621_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_pdf', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/consent'), upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_signed', models.BooleanField(default=False)),
                ('date_signed', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
