# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-08 16:44
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0012_consentpdf_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentpdf',
            name='consent_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/consent/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/consent'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gene_pc_api.ConsentPDF'),
        ),
    ]
