# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0013_auto_20160708_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='user',
            new_name='consent_pdf',
        ),
        migrations.AlterField(
            model_name='activityanswer',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_answers', to='gene_pc_api.Activity'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='gene_pc_api.Condition'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='gene_pc_api.Population'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
