# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene_pc_api', '0014_auto_20160719_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentpdf',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
