# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
