# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_riskscore_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='multiple_scores_explanation',
            field=models.CharField(blank=True, max_length=5024),
        ),
        migrations.AddField(
            model_name='condition',
            name='risk_explanation',
            field=models.CharField(blank=True, max_length=5024),
        ),
        migrations.AddField(
            model_name='condition',
            name='supporting_evidence',
            field=models.CharField(blank=True, max_length=5024),
        ),
    ]
