# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-02 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160907_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='condition',
            name='follow_up_activity_identifier',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
