# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-01 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170221_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(blank=True, max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
