# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170221_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityanswer',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitystatus',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ancestry',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
