# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-02 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_activityscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityscore',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='activityscore',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activityscore',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityscore',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
