# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170321_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_tracked_serverside',
            field=models.BooleanField(default=True),
        ),
    ]
