# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-06 18:43
from __future__ import unicode_literals

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.core.exceptions import ObjectDoesNotExist


def move_health_sample_identifiers_to_new_identifier_model(apps, schema_editor):
    HealthSample = apps.get_model('api', 'HealthSample')
    HealthSampleIdentifier = apps.get_model('api', 'HealthSampleIdentifier')

    for sample in HealthSample.objects.all():
        # Get the current value of an identifier or create it using the
        # HealthSample's existing data
        try:
            identifier = HealthSampleIdentifier.objects.get(identifier=sample.identifier)
        except ObjectDoesNotExist:
            identifier = HealthSampleIdentifier(identifier=sample.identifier)
            identifier.save()

        # Update the value of the identifier.
        sample.identifier = identifier.id
        sample.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activity_is_tracked_serverside'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSampleIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.RunPython(
            move_health_sample_identifiers_to_new_identifier_model
        ),
        migrations.AlterField(
            model_name='healthsample',
            name='identifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.HealthSampleIdentifier'),
        ),
        migrations.AlterUniqueTogether(
            name='activitystatus',
            unique_together=set([('user', 'activity', 'created_on')]),
        ),
    ]
