# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170302_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityscore',
            name='delta',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
