# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 23:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170406_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('identifier', models.CharField(blank=True, max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleMetricGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('conditions', models.ManyToManyField(blank=True, to='api.Condition')),
                ('metric', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.LifestyleMetric')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleMetricScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_personal_best', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleMetricSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('activities', models.ManyToManyField(blank=True, to='api.Activity')),
                ('conditions', models.ManyToManyField(blank=True, to='api.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleMetricStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.LifestyleMetric')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='healthsampleidentifier',
            old_name='identifier',
            new_name='value',
        ),
        migrations.AddField(
            model_name='lifestylemetricseries',
            name='health_sample_identifiers',
            field=models.ManyToManyField(blank=True, to='api.HealthSampleIdentifier'),
        ),
        migrations.AddField(
            model_name='lifestylemetricseries',
            name='metric',
            field=models.ManyToManyField(blank=True, related_name='series', to='api.LifestyleMetric'),
        ),
        migrations.AddField(
            model_name='lifestylemetricscore',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='api.LifestyleMetricSeries'),
        ),
        migrations.AddField(
            model_name='lifestylemetricscore',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lifestylemetricgoal',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.LifestyleMetricSeries'),
        ),
        migrations.AlterUniqueTogether(
            name='lifestylemetricstatus',
            unique_together=set([('metric', 'user')]),
        ),
    ]
