# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-09 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_activityscore_delta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityanswer',
            unique_together=set([('user', 'question_identifier', 'activity')]),
        ),
    ]
