# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170407_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifestylemetricseries',
            name='units',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
