# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lifestylemetricseries_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReductor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100)),
                ('value', models.FloatField(blank=True, default=-1.0, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductor', to='api.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='RiskReductorOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=100)),
                ('value', models.FloatField(blank=True, default=-1.0, max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('reductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.RiskReductor')),
            ],
        ),
    ]
