# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170516_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskreductoroption',
            name='active',
        ),
    ]
