# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20170516_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskreductor',
            name='value',
            field=models.FloatField(blank=True, default=-1.0, max_length=100, null=True),
        ),
    ]
