# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-08 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170516_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('link', models.URLField()),
                ('title', models.CharField(max_length=300)),
                ('image', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=450, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
