# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-28 22:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20170627_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentpdf',
            name='consent_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/data/consent/', location='/Users/ifoundit/Dropbox/Scripps/projects/gene-pc/gene-pc-api/data/consent'), upload_to=''),
        ),
    ]
