# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-02 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_riskreductor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskreductor',
            name='active',
        ),
        migrations.RemoveField(
            model_name='riskreductor',
            name='value',
        ),
    ]
