# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_condition_risk_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='version',
            field=models.CharField(default='', max_length=10),
        ),
    ]
