# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-10-18 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_trackedevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackedevent',
            name='featured',
        ),
    ]
